### get carts index
GET http://localhost:3000/carts.json

### Owners create (signup)
POST http://localhost:3000/owners.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### post carts create 
POST http://localhost:3000/carts.json
Content-Type: application/json

{
  "name": "Chinti's Tacos II",
  "location": "17th and Wolff St",
  "longitude": "-105.048627",
  "latitude": "39.744137",
  "email": "chinti@chinti.com",
  "phone_number": "7209878765",
  "image_url": ""
}

### patch carts update
PATCH http://localhost:3000/carts/3.json
Content-Type: application/json

{
  "name": "Tacos Jaliscos",
  "location": "20th and Wazee",
  "latitude": "39.754971979447596",
  "longitude": "-104.99546343634663",
  "email": "sallystacos@tacos.com",
  "phone_number": "720-458-0998",
  "image_url": "https://s3-media0.fl.yelpcdn.com/bphoto/HA6_t6oW5o7wfeH912D-Ew/348s.jpg"
}

### get show for frontend edit feature
GET http://localhost:3000/carts/6.json

