### get carts index
GET http://localhost:3000/carts.json

### get shortest_routes path index
GET http://localhost:3000/shortest_routes.json

### Owners create (signup)
POST http://localhost:3000/owners.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### post carts create 
POST http://localhost:3000/carts.json
Content-Type: application/json

{
  "name": "Chinti's Tacos II",
  "location": "17th and Wolff St",
  "longitude": "-105.048627",
  "latitude": "39.744137",
  "email": "chinti@chinti.com",
  "phone_number": "7209878765",
  "image_url": ""
}

### patch carts update
PATCH http://localhost:3000/carts/5.json
Content-Type: application/json

{
  "name": "Ruby's Treats",
  "location": "W. 23rd and Eliot St",
  "latitude": "39.751310",
  "longitude": "-105.023577",
  "email": "ruby@ruby.com.com",
  "phone_number": "720-458-0567",
  "image_url": "https://roaminghunger.com/blog/wp-content/uploads/2022/05/Gs-Taco-Spot-Los-Angeles.jpg"
}

### get show for frontend edit feature
GET http://localhost:3000/carts/6.json

